"use client";

import { useEffect, useState } from "react";

interface Account {
  id: string;
  platform: string;
  handle: string;
}

const PLATFORMS = ["TIKTOK", "YOUTUBE", "INSTAGRAM"] as const;

export function ScheduleDialog({
  clip,
  onClose,
}: {
  clip: { id: string; title: string };
  onClose: () => void;
}) {
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [platform, setPlatform] = useState<(typeof PLATFORMS)[number]>("TIKTOK");
  const [accountId, setAccountId] = useState<string>("");
  const [when, setWhen] = useState(() => defaultWhen());
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [done, setDone] = useState(false);

  useEffect(() => {
    fetch("/api/social/accounts")
      .then((r) => r.json())
      .then((d) => setAccounts(d.accounts ?? []))
      .catch(() => {});
  }, []);

  async function submit() {
    setBusy(true);
    setError(null);
    try {
      const res = await fetch("/api/schedule", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          clipId: clip.id,
          platform,
          scheduledAt: new Date(when).toISOString(),
          socialAccountId: accountId || undefined,
          generateMeta: true,
        }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Failed to schedule");
      setDone(true);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4" onClick={onClose}>
      <div className="card w-full max-w-md p-6" onClick={(e) => e.stopPropagation()}>
        {done ? (
          <div className="text-center">
            <div className="text-4xl">✅</div>
            <h3 className="mt-2 text-lg font-semibold">Scheduled!</h3>
            <p className="mt-1 text-sm text-slate-400">
              AI generated the title, description, and hashtags. View it on your calendar.
            </p>
            <button onClick={onClose} className="btn-primary mt-5 w-full">Done</button>
          </div>
        ) : (
          <>
            <h3 className="text-lg font-semibold">Schedule clip</h3>
            <p className="mt-1 line-clamp-1 text-sm text-slate-400">{clip.title}</p>

            <div className="mt-4">
              <label className="label">Platform</label>
              <div className="flex gap-2">
                {PLATFORMS.map((p) => (
                  <button
                    key={p}
                    onClick={() => setPlatform(p)}
                    className={`badge ${platform === p ? "bg-brand-500 text-white" : "bg-white/10 text-slate-300"}`}
                  >
                    {p}
                  </button>
                ))}
              </div>
            </div>

            <div className="mt-4">
              <label className="label">Account</label>
              <select className="input" value={accountId} onChange={(e) => setAccountId(e.target.value)}>
                <option value="">Default / not connected</option>
                {accounts.filter((a) => a.platform === platform).map((a) => (
                  <option key={a.id} value={a.id}>{a.handle}</option>
                ))}
              </select>
            </div>

            <div className="mt-4">
              <label className="label">When</label>
              <input type="datetime-local" className="input" value={when} onChange={(e) => setWhen(e.target.value)} />
            </div>

            <p className="mt-3 text-[11px] text-slate-500">
              Title, description, and hashtags are auto-generated by AI on schedule.
            </p>
            {error && <p className="mt-2 text-sm text-rose-400">{error}</p>}

            <div className="mt-5 flex gap-2">
              <button onClick={onClose} className="btn-ghost flex-1">Cancel</button>
              <button onClick={submit} disabled={busy} className="btn-primary flex-1">
                {busy ? "Scheduling…" : "Schedule"}
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

function defaultWhen() {
  const d = new Date(Date.now() + 60 * 60 * 1000);
  d.setMinutes(0, 0, 0);
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
}
